name: learning
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - expat=2.5.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.12.2
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - astroid==3.1.0
      - dill==0.3.8
      - isort==5.13.2
      - mccabe==0.7.0
      - platformdirs==4.2.0
      - ruff==0.3.0
      - tomlkit==0.12.4
